Repository mrwybraniec/nonsymmetrical-narvanso, pull requests merged in 2023-01, with the labels that each got.

#6 Setup the project dependencies
  README.md
  pyproject.toml
Labels: good first issue

#5 Create dependabot.yml
  .github/dependabot.yml
Labels: good first issue

#8 Update the project setup
  pyproject.toml
Labels: documentation, invalid

#10 Add `CODEOWNERS` to the repo
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, good first issue

#12 Initialise the django project
  .gitignore
  app/__init__.py
  app/asgi.py
  app/settings.py
  app/urls.py
  app/wsgi.py
  crawler/__init__.py
  crawler/admin.py
  crawler/apps.py
  crawler/migrations/__init__.py
  crawler/models.py
  crawler/tests.py
  crawler/views.py
  manage.py
  poetry.lock
Labels: enhancement, good first issue
